version: '3.9'
services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    command: npm run dev
    stdin_open: true
    tty: true
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '28081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=$DB_HOST
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGODB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongo://$MONGODB_USER:$MONGODB_PASSWORD@$DB_HOST:$DB_PORT/
    depends_on:
      - mongodb
volumes:
  redis:
    driver: local
  db:
